---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-"
)
```
# phylotree

The goal of phylotree is to ...

## Installation

You can install phylotree from github with:

```{r gh-installation, eval = FALSE}
# install.packages("devtools")
devtools::install_github("zachcp/phyloTreeWidget")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
## basic example code
phylotree("Booyah! I plot the Zika TREE!")
phylotree("Booyah! I plot the Zika TREE!", width=300, height=300)
```

```{r}

tree <- ape::read.tree(text="(A, (B, C), (D, E), F);")
data <- data.frame(
  node = c("A", "B", "C", "D", "E", "F"),
  lat = c(10,11,12,13,14, 15),
  kind = c("AA", "BA", "CA", "DA", "EA", "FA"))

json1 <- process_tree(tree, data, python="/Users/zach/anaconda3/bin/python")

phylotree(tree, data, python="/Users/zach/anaconda3/bin/python")

```

```{r}
library(ape)
data("bird.families")
bird.families
birddata <- data.frame(
  node = bird.families$tip.label,
  col1 = sample(1:5, length(bird.families$tip.label), replace=T),
  col2 = sample(1:20, length(bird.families$tip.label), replace=T),
  col4 = sample(LETTERS[1:10], length(bird.families$tip.label), replace=T)
)
create_colormaps(birddata)
phylotree(tree=bird.families, data=birddata, python="/Users/zach/anaconda3/bin/python")
```
